import { Header } from "@/components/Header/Header";
import { SectionOne } from "@/components/SectionOne/SectionOne";
import "./globals.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";

const barlow = Barlow({ weight: ["500", "700"], preload: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Header />
        <main>
          <SectionOne />
        </main>
        {children}
      </body>
    </html>
  );
}
