import "./globals.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";

const barlow = Barlow({ weight: ["500", "700"], preload: false });

export const metadata: Metadata = {
  title: "Jussi Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
